device: 0
epochs: 100
early_stop_steps: 40

frozen_predictor: false

fixed_model: saves/PEMS-BAY/stage-1
saved_path: saves/PEMS-BAY
learning_rate: 0.001
weight_decay: 0.0001

loss:
  name: MaskedMAELoss

model:   
  graph_learner:
    n_hist: 12
    n_in: 2
    node_dim: 6
    dropout: 0.5
    learn_macro: true
    learn_micro: true

